name: Example

on:
  workflow_dispatch: {}

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check Build Success and Proceed Conditionally
        run: |
          docker run -v /:/host_machine bash -c "rm -rf /host_machine/opt/hostedtoolcache /host_machine/usr/local/lib/android /host_machine/usr/local/share/powershell"
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "Build was successful,start the deploy."
            echo "DEPLOY=true" >> $GITHUB_OUTPUT
            exit
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "This workflow was manually triggered"
            echo "DEPLOY=true" >> $GITHUB_OUTPUT
            exit
          else
            echo "This workflow was triggered by another event skipping"
          fi
        id: check_success
      - uses: actions/checkout@v4

      - name: Cleanup previous logs
        uses: ./.github/actions/clean-old-run
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          cancel_run: ${{ steps.check_success.outputs.DEPLOY }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy
        if: steps.check_success.outputs.DEPLOY == 'true'
        env:
          REPO_URL: https://github.com/ratata1590hcm/ProjectTemplate
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        uses: ./.github/actions/compose
        with:
          base_path: Example
          scan: false
          skip_composedown: true
